INSERT INTO Company VALUES ('AAD', 'Ardent Leisure Group', '61 Lavender Street Level 16 Milsons Point, NSW', '2061', 'Australia');
INSERT INTO Company VALUES ('ABC', 'Adelaide Brighton Limited', '157 Grenfell Street Level 1 Adelaide, SA', '5000', 'Australia');
INSERT INTO Company VALUES ('ABP', 'Abacus Property Group', 'Square Level 34 Sydney, NSW', '2000', 'Australia');
INSERT INTO Company VALUES ('ACR', 'Acrux Limited', '103-113 Stanley Street West Melbourne, VIC', '3003', 'Australia');
INSERT INTO Company VALUES ('AGK', 'AGL Energy Limited', '101 Miller Street Level 22 North Sydney, NSW', '2060', 'Australia');
INSERT INTO Company VALUES ('AGO', 'Atlas Iron Ltd', 'Raine Square Level 18 Perth, WA', '6000', 'Australia');
INSERT INTO Company VALUES ('AIO', 'Asciano Limited', '15 Blue Street Level 6 North Sydney, NSW', '2060', 'Australia');
INSERT INTO Company VALUES ('ALL', 'Aristocrat Leisure Limited', 'Pinnacle Office Park Building A North Ryde, NSW', '2113', 'Australia');
INSERT INTO Company VALUES ('ALZ', 'Australand Property Group', 'Building C Level 3 Rhodes, NSW', '2138', 'Australia');
INSERT INTO Company VALUES ('AMC', 'Amcor Limited', '109 Burwood Road Hawthorn, VIC', '3122', 'Australia');
INSERT INTO Company VALUES ('AMP', 'AMP Limited', 'Level 24 33 Alfred Street Sydney, NSW', '2000', 'Australia');
INSERT INTO Company VALUES ('ANN', 'Ansell Limited', '678 Victoria Street Level 3 Richmond, VIC', '3121', 'Australia');
INSERT INTO Company VALUES ('ANZ', 'ANZ Banking Group Ltd.', 'ANZ Centre Melbourne Level 9 Melbourne, VIC', '3008', 'Australia');
INSERT INTO Company VALUES ('APN', 'APN News and Media Ltd.', '100 William Street Level 4 Sydney, NSW', '2011', 'Australia');
INSERT INTO Company VALUES ('AQA', 'Aquila Resources Limited', 'Aquila Centre Level 2 Como, WA', '6152', 'Australia');
INSERT INTO Company VALUES ('AQP', 'Aquarius Platinum Ltd', 'Clarendon House 2 Church Street Hamilton, HM CX', '', 'Bermuda');
INSERT INTO Company VALUES ('ASL', 'Ausdrill Limited', '6-12 Uppsala Place Canning Vale, WA', '6155', 'Australia');\Q
INSERT INTO Company VALUES ('ASX', 'ASX Limited', 'Exchange Centre 20 Bridge Street Sydney, NSW', '2000', 'Australia');
INSERT INTO Company VALUES ('AUT', 'Aurora Oil & Gas Ltd.', '77 St George''s Terrace Level 20 Perth, WA', '6000', 'Australia');
INSERT INTO Company VALUES ('AWC', 'Alumina Ltd', 'IBM Centre Level 12 Southbank, VIC', '3006', 'Australia');
INSERT INTO Company VALUES ('AWE', 'AWE Ltd.', '40 Mount Street Level 16 North Sydney, NSW', '2060', 'Australia');
INSERT INTO Rating(Code) VALUES ('AAD');
INSERT INTO Rating(Code) VALUES ('ABC');
INSERT INTO Rating(Code) VALUES ('ABP');
INSERT INTO Rating(Code) VALUES ('ACR');
INSERT INTO Rating(Code) VALUES ('AGK');
INSERT INTO Rating(Code) VALUES ('AGO');
INSERT INTO Rating(Code) VALUES ('AIO');
INSERT INTO Rating(Code) VALUES ('ALL');
INSERT INTO Rating(Code) VALUES ('ALZ');
INSERT INTO Rating(Code) VALUES ('AMC');
INSERT INTO Rating(Code) VALUES ('AMP');
INSERT INTO Rating(Code) VALUES ('ANN');
INSERT INTO Rating(Code) VALUES ('ANZ');
INSERT INTO Rating(Code) VALUES ('APN');
INSERT INTO Rating(Code) VALUES ('AQA');
INSERT INTO Rating(Code) VALUES ('AQP');
INSERT INTO Rating(Code) VALUES ('ASL');
INSERT INTO Rating(Code) VALUES ('ASX');
INSERT INTO Rating(Code) VALUES ('AUT');
INSERT INTO Rating(Code) VALUES ('AWC');
INSERT INTO Rating(Code) VALUES ('AWE');
INSERT INTO Executive VALUES('AAD', 'Mr. Neil R. Balnaves AO');
INSERT INTO Executive VALUES('AAD', 'Mr. Gregory D. Shaw');
INSERT INTO Executive VALUES('AAD', 'Mr. Richard M. Johnson');
INSERT INTO Executive VALUES('AAD', 'Mr. Roy Menachemson');
INSERT INTO Executive VALUES('AAD', 'Mr. Charlie Keegan');
INSERT INTO Executive VALUES('ABC', 'Mr. Mark P. Chellew BSc, ME, Grad Diploma Mgt');
INSERT INTO Executive VALUES('ABC', 'Mr. Michael Kelly');
INSERT INTO Executive VALUES('ABC', 'Mr. Marcus R. D. Clayton');
INSERT INTO Executive VALUES('ABC', 'Ms. Sam J. Toppenberg');
INSERT INTO Executive VALUES('ABC', 'Mr. Martin Brydon');
INSERT INTO Executive VALUES('ABP', 'Dr. Frank Wolf OAM, Ph.D., BA');
INSERT INTO Executive VALUES('ABP', 'Mr. Ellis Varejes B.Com., L.L.B.');
INSERT INTO Executive VALUES('ABP', 'Mr. Len Lloyd F.A.P.I., W.D.A., LREA.');
INSERT INTO Executive VALUES('ABP', 'Mr. Peter Strain');
INSERT INTO Executive VALUES('ABP', 'Mr. John L''estrange');
INSERT INTO Executive VALUES('ACR', 'Mr. Ross Dobinson B. Bus (Acc)');
INSERT INTO Executive VALUES('ACR', 'Mr. Clive Blower BSc (Hons), Ph.D.');
INSERT INTO Executive VALUES('ACR', 'Tony Di Pietro');
INSERT INTO Executive VALUES('ACR', 'Dr. Nina Webster Ph.D., M.IP.Law');
INSERT INTO Executive VALUES('AGK', 'Mr. Michael Anthony Fraser BCom, CPA, FTIA');
INSERT INTO Executive VALUES('AGK', 'Mr. Paul McWilliams BA (Accounting), MApFin, GradDipACG, ACA, ACSA, AC');
INSERT INTO Executive VALUES('AGK', 'Mr. Michael Patrick Moraza BE (Chem. Eng.), MBA');
INSERT INTO Executive VALUES('AGK', 'Mr. Stephen John Mikkelsen BBS, CA');
INSERT INTO Executive VALUES('AGK', 'Mr. Anthony Fowler BSc (Hons), MAppFin, Harvard AMP, FFin');
INSERT INTO Executive VALUES('AGO', 'Mr. Kenneth Edward Brinsden B.Eng, WASM, MAusImm');
INSERT INTO Executive VALUES('AGO', 'Mr. Mark D. Hancock B.Bus, CA, FFin');
INSERT INTO Executive VALUES('AGO', 'Mr. Jeremy Andrew Sinclair B.Eng. (Mining), MAusImm');
INSERT INTO Executive VALUES('AGO', 'Mr. Robert Wilson Bsc. Eng, Mba, Maicd, Ot');
INSERT INTO Executive VALUES('AGO', 'Ms. Kathleen Bozanic B.Com, ACA');
INSERT INTO Executive VALUES('AIO', 'Mr. John Patrick Mullen Bsc');
INSERT INTO Executive VALUES('AIO', 'Mr. Roger L. Burrows BCom, CPA, MAICD');
INSERT INTO Executive VALUES('AIO', 'Mr. Angus R. McKay');
INSERT INTO Executive VALUES('AIO', 'Mr. David Irwin');
INSERT INTO Executive VALUES('AIO', 'Mr. Alistair Field');
INSERT INTO Executive VALUES('ALL', 'Mr. Jamie R. Odell MBA');
INSERT INTO Executive VALUES('ALL', 'Mrs. Antonia Korsanos');
INSERT INTO Executive VALUES('ALL', 'Mr. Trevor J. Croker');
INSERT INTO Executive VALUES('ALL', 'Mr. Atul Bali');
INSERT INTO Executive VALUES('ALL', 'Mr. Manjit Gombra Singh');
INSERT INTO Executive VALUES('ALZ', 'Mr. Robert William Johnston B. Eng (Electrical) (Hons 1)');
INSERT INTO Executive VALUES('ALZ', 'Mr. Kieran Pryke B. Com, FCPA');
INSERT INTO Executive VALUES('ALZ', 'Mr. Sean McMahon');
INSERT INTO Executive VALUES('ALZ', 'Mr. Rodney Vaughan Fehring');
INSERT INTO Executive VALUES('ALZ', 'Mr. Michael Bowden Newsom FCIS, BA, LLB');
INSERT INTO Executive VALUES('AMC', 'Mr. John Kenneth Norman MacKenzie B.Eng, FIEA');
INSERT INTO Executive VALUES('AMC', 'Mr. Ron Delia BSc (Marketing), MBA');
INSERT INTO Executive VALUES('AMC', 'Mr. Ian G. Wilson LLB (Hons), LLM');
INSERT INTO Executive VALUES('AMC', 'Mr. Peter Brues B. Comm., CA');
INSERT INTO Executive VALUES('AMC', 'Mr. Nigel D. Garrard BEc., ACA, MAICD');
INSERT INTO Executive VALUES('AMP', 'Mr. Craig William Dunn BCom, FCA');
INSERT INTO Executive VALUES('AMP', 'Mr. Colin Grahame Storrie B.Com, GradDipMgt, CPA, MAICD');
INSERT INTO Executive VALUES('AMP', 'Mr. Lee Barnett');
INSERT INTO Executive VALUES('AMP', 'Mr. Brian Salter BA, LLB (Hons), LLM (Hons), MAICD, F.ASF');
INSERT INTO Executive VALUES('AMP', 'Mr. Fiona Wardlaw');
INSERT INTO Executive VALUES('ANN', 'Mr. Magnus R. Nicolin BA, MBA (Wharton)');
INSERT INTO Executive VALUES('ANN', 'Mr. Steve Genzer BSc, MBA');
INSERT INTO Executive VALUES('ANN', 'Mr. Thomas Draskovics BA (Chem), MBA');
INSERT INTO Executive VALUES('ANN', 'Mr. Scott R. Corriveau BA (Bus Admin), MBA');
INSERT INTO Executive VALUES('ANN', 'Mr. Peter B. Carroll BEng, MBA');
INSERT INTO Executive VALUES('ANZ', 'Mr. John Powell Morschel Dip. Q.S., F.A.I.M., F.A.I.C.D.');
INSERT INTO Executive VALUES('ANZ', 'Mr. Michael Roger Pearson Smith O.B.E., B.Sc. (Hons.)');
INSERT INTO Executive VALUES('ANZ', 'Mr. Graham Kennedy Hodges BEc (Hons)');
INSERT INTO Executive VALUES('ANZ', 'Mr. David Duncan Hisco B Bus, MBA');
INSERT INTO Executive VALUES('ANZ', 'Mr. Shayne Cary Elliott B.Com');
INSERT INTO Executive VALUES('APN', 'Mr. Jeff Howard');
INSERT INTO Executive VALUES('APN', 'Mr. Martin Simons');
INSERT INTO Executive VALUES('APN', 'Mr. Warren Lee');
INSERT INTO Executive VALUES('APN', 'Mr. Michael Miller');
INSERT INTO Executive VALUES('APN', 'Neil Monagha');
INSERT INTO Executive VALUES('AQA', 'Mr. Anthony Poli B.Com.,CPA, FTIA, MAICD');
INSERT INTO Executive VALUES('AQA', 'Mr. Stephen J. Pilcher B.Eng (Mining, Hons), B.Ec');
INSERT INTO Executive VALUES('AQA', 'Mr. Martin N. Alciaturi B.Sc (Eng) (Hons), CA');
INSERT INTO Executive VALUES('AQA', 'Mr. Howard C. Rae B.Com, CA');
INSERT INTO Executive VALUES('AQA', 'Mr. Jason A. Pavy Ll.B (Hons), B.Com');
INSERT INTO Executive VALUES('AQP', 'Mr. Jean Johannes Nel CFA');
INSERT INTO Executive VALUES('AQP', 'Mr. Winston Chitando B Acc');
INSERT INTO Executive VALUES('AQP', 'Mr. Robert Neville Schroder');
INSERT INTO Executive VALUES('AQP', 'Mr. Willi M.P. Boehm Bbus (Acc)');
INSERT INTO Executive VALUES('AQP', 'Mr. Gabriel de Wet B.Sc. Eng (Mech)');
INSERT INTO Executive VALUES('ASL', 'Mr. Ronald George Sayers');
INSERT INTO Executive VALUES('ASL', 'Mr. Jos E. Martins BACC,CA(SA)');
INSERT INTO Executive VALUES('ASL', 'Mr. Alex J. McCulloch');
INSERT INTO Executive VALUES('ASL', 'Mr. John Kavanagh');
INSERT INTO Executive VALUES('ASL', 'M. C. Crocker');
INSERT INTO Executive VALUES('ASX', 'Mr. Elmer Funke Kupper MBA');
INSERT INTO Executive VALUES('ASX', 'Mr. Ramy Aziz');
INSERT INTO Executive VALUES('ASX', 'Mr. Tim J. Hogben');
INSERT INTO Executive VALUES('ASX', 'Mr. Tim Thurman');
INSERT INTO Executive VALUES('ASX', 'Ms. Amanda J. Harkness BEc LLB (Hons) (ANU), MA (Macquarie), FCIS, FAIM');
INSERT INTO Executive VALUES('AUT', 'Mr. Jonathan Kingsley Stewart B.Com, CA');
INSERT INTO Executive VALUES('AUT', 'Mr. Douglas E. Brooks');
INSERT INTO Executive VALUES('AUT', 'Mr. Michael L. Verm');
INSERT INTO Executive VALUES('AUT', 'Mr. J. David Lucke');
INSERT INTO Executive VALUES('AUT', 'Mr. Darren Wasylucha');
INSERT INTO Executive VALUES('AWC', 'Mr. John Andrew Bevan BCom');
INSERT INTO Executive VALUES('AWC', 'Mr. Chris Thiris B.A (Acc), MBA, CA, F.Fin, CFTP');
INSERT INTO Executive VALUES('AWC', 'Mr. Stephen C. Foster BCom, LLB(Hons), GDipAppFin (Sec Inst), GradDip CS');
INSERT INTO Executive VALUES('AWC', 'Mr. Alan Dundas B.E. (Hons.), F.Aus.I.M.M., G.A.I.C.D.');
INSERT INTO Executive VALUES('AWE', 'Mr. Bruce Frederick William Clement BSc, BEng (Hons), MBA');
INSERT INTO Executive VALUES('AWE', 'Ms. Ayten Saridas');
INSERT INTO Executive VALUES('AWE', 'Mr. Dennis Washer');
INSERT INTO Executive VALUES('AWE', 'Mr. Neville Francis Kelly B.Com (Merit), CPA');
INSERT INTO Executive VALUES('AWE', 'Mr. David R. N. Gaudoin');
INSERT INTO ASX VALUES('2012-01-03','AAD','171200','0.91');
INSERT INTO ASX VALUES('2012-01-03','ABC','383100','2.64');
INSERT INTO ASX VALUES('2012-01-03','ABP','1334700','1.78');
INSERT INTO ASX VALUES('2012-01-03','ACR','203000','2.93');
INSERT INTO ASX VALUES('2012-01-03','AGK','355200','13.55');
INSERT INTO ASX VALUES('2012-01-03','AGO','2406000','2.69');
INSERT INTO ASX VALUES('2012-01-03','AIO','1773700','4.51');
INSERT INTO ASX VALUES('2012-01-03','ALL','419500','2.16');
INSERT INTO ASX VALUES('2012-01-03','ALZ','416200','2.23');
INSERT INTO ASX VALUES('2012-01-03','AMC','1223800','6.73');
INSERT INTO ASX VALUES('2012-01-03','AMP','3399800','3.89');
INSERT INTO ASX VALUES('2012-01-03','ANN','191600','14.23');
INSERT INTO ASX VALUES('2012-01-03','ANZ','4087000','19.02');
INSERT INTO ASX VALUES('2012-01-03','APN','667500','0.68');
INSERT INTO ASX VALUES('2012-01-03','AQA','144300','6.07');
INSERT INTO ASX VALUES('2012-01-03','AQP','421000','2.45');
INSERT INTO ASX VALUES('2012-01-03','ASL','789800','2.85');
INSERT INTO ASX VALUES('2012-01-03','ASX','166600','27.63');
INSERT INTO ASX VALUES('2012-01-03','AUT','380800','3.44');
INSERT INTO ASX VALUES('2012-01-03','AWC','10153700','1.11');
INSERT INTO ASX VALUES('2012-01-03','AWE','692700','1.31');
INSERT INTO ASX VALUES('2012-01-04','AAD','766300','0.92');
INSERT INTO ASX VALUES('2012-01-04','ABC','701700','2.68');
INSERT INTO ASX VALUES('2012-01-04','ABP','587000','1.80');
INSERT INTO ASX VALUES('2012-01-04','ACR','481900','2.99');
INSERT INTO ASX VALUES('2012-01-04','AGK','1287900','13.89');
INSERT INTO ASX VALUES('2012-01-04','AGO','5563600','2.78');
INSERT INTO ASX VALUES('2012-01-04','AIO','2839800','4.54');
INSERT INTO ASX VALUES('2012-01-04','ALL','1349000','2.19');
INSERT INTO ASX VALUES('2012-01-04','ALZ','1081900','2.26');
INSERT INTO ASX VALUES('2012-01-04','AMC','2974700','6.73');
INSERT INTO ASX VALUES('2012-01-04','AMP','11440700','3.93');
INSERT INTO ASX VALUES('2012-01-04','ANN','439200','14.24');
INSERT INTO ASX VALUES('2012-01-04','ANZ','8424800','19.33');
INSERT INTO ASX VALUES('2012-01-04','APN','963500','0.69');
INSERT INTO ASX VALUES('2012-01-04','AQA','192600','6.36');
INSERT INTO ASX VALUES('2012-01-04','AQP','569900','2.54');
INSERT INTO ASX VALUES('2012-01-04','ASL','1135100','2.85');
INSERT INTO ASX VALUES('2012-01-04','ASX','497600','28.03');
INSERT INTO ASX VALUES('2012-01-04','AUT','1243200','3.44');
INSERT INTO ASX VALUES('2012-01-04','AWC','14970400','1.14');
INSERT INTO ASX VALUES('2012-01-04','AWE','2050500','1.35');

